<?xml version="1.0"?>
<package format="2">
  <name>pal_pro_gripper_description</name>
  <version>0.0.4</version>
  <description>The pal_pro_gripper_description package</description>

  <maintainer email="david.terkuile@pal-robotics.com">David ter Kuile</maintainer>
  <author email="david.terkuile@pal-robotics.com">David ter Kuile</author>

  <license>BSD</license>

  <buildtool_depend>catkin</buildtool_depend>
  <exec_depend>xacro</exec_depend>
  <exec_depend>roboticsgroup_upatras_gazebo_plugins</exec_depend>
  <exec_depend>rosbash</exec_depend>
  <exec_depend>pal_urdf_utils</exec_depend>

  <test_depend>rostest</test_depend>
  <test_depend>urdf_test</test_depend>
</package>
